### ISSUE TITLE
java.lang.IllegalStateException: Cannot start this animator on a detached view!

### ISSUE THREAD

**Issue by yangkong** [zzz40500/AndroidSweetSheet#10]
java.lang.IllegalStateException: Cannot start this animator on a detached view!
	at android.view.RenderNode.addAnimator(RenderNode.java:817)
	at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:277)
	at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:261)
	at android.animation.RevealAnimator.<init>(RevealAnimator.java:37)
	at android.view.ViewAnimationUtils.createCircularReveal(ViewAnimationUtils.java:48)
	at com.mingle.widget.CircleRevealHelper.circularReveal(CircleRevealHelper.java:64)
	at com.mingle.widget.CircleRevealHelper.circularReveal(CircleRevealHelper.java:52)
	at com.mingle.widget.CRImageView.circularReveal(CRImageView.java:84)
	at com.mingle.sweetpick.CustomDelegate$AnimationImp.onEnd(CustomDelegate.java:180)
	at com.mingle.widget.SweetView$4.onAnimationEnd(SweetView.java:126)
	at com.nineoldandroids.animation.ValueAnimator.endAnimation(ValueAnimator.java:1034)
	at com.nineoldandroids.animation.ValueAnimator.access$900(ValueAnimator.java:43)
	at com.nineoldandroids.animation.ValueAnimator$AnimationHandler.handleMessage(ValueAnimator.java:669)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5292)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

**Comment by Chickinnick** [comment]
+1 !This issue apears while animation in not yet finished user tries to toggle again

**Comment by followthemoney1** [comment]
Duplicate of #so how to fix it?

**Comment by sharvesh0608** [comment]
i have the same issue is there a fix?
