### ISSUE TITLE
 java.lang.IllegalStateException:

### ISSUE THREAD

**Issue by wang9090980** [zzz40500/AndroidSweetSheet#18]
java.lang.IllegalStateException: Cannot start this animator on a detached view!
                                                                      at android.view.RenderNode.addAnimator(RenderNode.java:812)
                                                                      at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:300)
                                                                      at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:282)
                                                                      at android.animation.RevealAnimator.<init>(RevealAnimator.java:37)
                                                                      at android.view.ViewAnimationUtils.createCircularReveal(ViewAnimationUtils.java:55)
                                                                      at com.mingle.widget.CircleRevealHelper.circularReveal(CircleRevealHelper.java:64)
                                                                      at com.mingle.widget.CircleRevealHelper.circularReveal(CircleRevealHelper.java:52)
                                                                      at com.mingle.widget.CRImageView.circularReveal(CRImageView.java:84)
                                                                      at com.mingle.sweetpick.CustomDelegate$AnimationImp.onEnd(CustomDelegate.java:180)
                                                                      at com.mingle.widget.SweetView$4.onAnimationEnd(SweetView.java:126)
                                                                      at com.nineoldandroids.animation.ValueAnimator.endAnimation(ValueAnimator.java:1034)
                                                                      at com.nineoldandroids.animation.ValueAnimator.access$900(ValueAnimator.java:43)
                                                                      at com.nineoldandroids.animation.ValueAnimator$AnimationHandler.handleMessage(ValueAnimator.java:669)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5438)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by jmheart** [comment]
我也遇到了这个问题， 请问一下， 你解决了吗

**Comment by wang9090980** [comment]
还没有呢，我发现在6.0的系统上都有问题
