### ISSUE TITLE
作者，你好，我遇到一个bug。

### ISSUE THREAD

**Issue by HomHomLin** [zzz40500/AndroidSweetSheet#6]
作者你好，这个库，相当不错，我使用和分析代码后，将其运用到自己的项目中，结果在使用过程中出现了一个bug：
10-21 12:36:57.174 16444-16444/com.kascend.chushou E/AndroidRuntime﹕ FATAL EXCEPTION: main
java.lang.NullPointerException
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2821)
at android.view.View.draw(View.java:13513)
at android.view.View.getDisplayList(View.java:12461)
at android.view.View.getDisplayList(View.java:12505)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2934)
at android.view.View.getDisplayList(View.java:12397)
at android.view.View.getDisplayList(View.java:12505)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2934)
at android.view.View.getDisplayList(View.java:12397)
at android.view.View.getDisplayList(View.java:12505)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2934)
at android.view.View.getDisplayList(View.java:12397)
at android.view.View.getDisplayList(View.java:12505)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2934)
at android.view.View.getDisplayList(View.java:12397)
at android.view.View.getDisplayList(View.java:12505)
at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1187)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:2149)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2021)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1832)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4216)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
at android.view.Choreographer.doCallbacks(Choreographer.java:555)
at android.view.Choreographer.doFrame(Choreographer.java:525)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
at android.os.Handler.handleCallback(Handler.java:615)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5004)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:558)
at dalvik.system.NativeStart.main(Native Method)
上述log提示我绘制错误，我关闭硬件加速，出现softwaredraw的错误，不知道是什么地方的问题，这困惑了我很久。

**Comment by HomHomLin** [comment]
这个bug没有一个是库或者我的项目导致的，全部提示底层的bug，只有当我导入这个库之后，并且在连续快速调用sheet的toggle方法之后出现。

**Comment by zzz40500** [comment]
我会追踪这个bug的

**Comment by jmheart** [comment]
多次点击就会出现的， 应该是动画，在启动和销毁这个过程有个场景没有考虑到，就是多次连续点击的时
